### ISSUE TITLE
Code using undefined/erroneous behaviour

### ISSUE THREAD

**Issue by Yoplitein** [wootguy/Glitch-Life#1]
I've begun work on a port to Linux [on my fork](https://github.com/Yoplitein/Glitch-Life/tree/linux). Everything seems to work fine, for the most part.

The only issue I've had so far is in model_util.cpp, lines 1613, 1701, and 1707 (in the unported source):
```
ent_models.erase(it--);
```
After being yelled at by my compiler, and doing a little research, I've discovered that decrementing forward iterators is simply not allowed.

I have no idea what this is supposed to do. Googling only turns up cases where people have used this for reverse iteration, but that doesn't seem to be the case here. What would you suggest as a workaround?

**Comment by wootguy** [comment]
The point of that line was to continue from the next element after the current element was deleted. If it wasn't decremented there then the next element would be skipped.

The easiest way around this would be to not increment in the for loop, and only increment if erase wasn't called. Moving it++ from line 1576 to just after 1709 should do the trick (along with never decrementing it).

**Comment by wootguy** [comment]
It's kind of funny that worked at all. The point of decrementing there was to continue from the next element after the current one was erased. The next element would be skipped otherwise.

I just did a little research on this too. The erase method invalidates the iterator, so what I would do is increment instead of decrement at the calls to erase. That way we're not using an invalid iterator or doing illegal things. Then to make sure the next element isn't skipped, the it++ on line 1576 should be moved to just after 1709.

**Comment by Yoplitein** [comment]
> It's kind of funny that worked at all.

I've found a few things like that so far. What version of Visual Studio did you use for this?

**Comment by wootguy** [comment]
2012

**Comment by Yoplitein** [comment]
Excellent. After applying your fix, everything works beautifully on Linux.

**Comment by Yoplitein** [comment]
Also might have fixed other issues I was running in to on windows, could've been corrupting the memory etc.

**Comment by wootguy** [comment]
Awesome work!
