### ISSUE TITLE
Possible issues and questions. 

### ISSUE THREAD

**Issue by LossyDragon** [wootguy/Glitch-Life#11]
Hi woot! :)

I recently started getting back into GL to play with some friends, and I noticed a few things while generating maps. Sven 5.14

1. Bug:

The first issue is "FATAL ERROR (shutting down): Host_Error: Backwards mins/maxs in entity at X-1279.00 Y464.00 Z-1034.00: 9999.00/-9999.00", with the same error on a few other maps. The one quoted is from "<aug20_hl_c05_a3> that I have generated. 

Digging into the ripent that entity is the following: 
```
{
"origin" "-1279 464 -1034"
"rendercolor" "0 0 0"
"sequence" "37"
"angles" "0 269 0"
"body" "1"
"pose" "2"
"is_player_ally" ""
"displayname" "sat_globe scientist_dead"
"classname" "monster_scientist_dead"
}
```

I'm unable to find more information about this error. It could be that the model is clipping through a brush(?), or missing hullsize "0 0 0";  based on a quick glance at the map.

2. Question/Bug?? 

Another thing is that some configurations within the gsrand_config isn't being followed. Mostly scale and flip. With the config set (shown below) and used to generate another set of maps, scale isn't as noticeable, but map flipping is still being ignored. 

My config is: 
```
corruption_mode  = random
corruptions      = weird shift grey bw contrast invert
```
If you would like to see the maps for yourself, here are two files zipped for you. [Zip](http://www.lossydragon.com/tempdir/minsmaxs.zip)

**Comment by wootguy** [comment]
Thanks for linking the maps, that helped me find the problems right away.

> "FATAL ERROR (shutting down): Host_Error: Backwards mins/maxs"

That error comes up when the custom min/max hull sizes are set backwards. I tried adding minhullsize/maxhullsize keys on that ent but it still happened.

The problem seems to be with the model replacement used for that entity. I tried a few other replacement models and only the globe model triggered the crash.

"models/sat_globe.mdl" is now in the blacklist for monster_x_dead entities. Download the new gsrand_models.txt and hopefully it won't happen again.

> gsrand_config isn't being followed

You've got "Corrupt Mode : Super random" selected in the program. It should be set to "Use config settings" if you want to restrict corruptions to whatever is in the config file.
