### ISSUE TITLE
Setting 'gmr_only' to '0' has no effect whatsoever

### ISSUE THREAD

**Issue by dimmskii** [wootguy/Glitch-Life#15]
Setting 'gmr_only' to '0' in the config yields no results for me.

The program continues to randomize ent models using *_gmr.gsrand files. Furthermore, removing those files reverts the models and removes the randomization. I assume it means that not only do the files get generated, but "per-entity randomization" doesn't happen either.

**Comment by wootguy** [comment]
The game has a limit of ~512 unique models in a map. If the program [thinks it would exceed this limit](https://github.com/wootguy/Glitch-Life/blob/master/src/model_util.cpp#L1648) by doing per-entity replacement then it falls back to GMR-only mode. A lot of maps seem to be near this limit (even svencoop1 and hl_c01_01). Also, some entities can only be replaced through GMR, so there is almost always a GMR file regardless of what gmr_only is set to.

I tried toggling gmr_only for [island](http://scmapdb.com/map:island) and it worked for me. Each shark had its own model, and there was a GMR file for weapon model/sprite replacements.

The program should log when it falls back to GMR mode because I thought this was broken at first too.
