### ISSUE TITLE
It doesnt recognize any files.

### ISSUE THREAD

**Issue by HammBurglar** [wootguy/Glitch-Life#26]
It just says 0 Sounds, textures, models etc. found.

**Comment by HammBurglar** [comment]
![image](https://user-images.githubusercontent.com/105389465/167931760-8a5a355b-0edb-4099-bd36-b0d79e5ce14b.png)

**Comment by wootguy** [comment]
the full path to the program is `C:\Program Files (x86)\Steam\steamapps\common\Sven Co-op\svencoop_addon\gsrand.exe` ?

**Comment by HammBurglar** [comment]
yes @wootguy

**Comment by wootguy** [comment]
I guess you could try putting it in `/svencoop` instead of `/svencoop_addon`. Or maybe it doesn't like spaces in the folder path `Program Files (x86)`.

Generally this only happens when placed in a subfolder instead of the root of svencoop_addon (e.g. `/svencoop_addon/maps/gsrand.exe` instead of `svencoop_addon/gsrand.exe`).

**Comment by HammBurglar** [comment]
i already tried putting it in /svencoop but it just won`t execute.

**Comment by HammBurglar** [comment]
it says that its in the wrong directory and i should move it

**Comment by wootguy** [comment]
Last thing I can think to try is to follow the `Content Selection` instructions in the readme.

**Comment by HammBurglar** [comment]
it works now, thanks a lot
